<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!DOCTYPE html><html lang="vi"><head><meta charset="UTF-8"><title>Video - Thư viện số</title><link rel="stylesheet" href="${pageContext.request.contextPath}/css/style.css"></head><body>
<%@ include file="/views/_navbar.jsp" %><div class="container"><div class="card">
<div class="flex-between"><h1>Danh sách video</h1><c:if test="${sessionScope.currentUser.role == 'ADMIN' or sessionScope.currentUser.role == 'LIBRARIAN'}"><a href="${pageContext.request.contextPath}/videos/add" class="btn btn-primary">+ Thêm video</a></c:if></div>
<form action="${pageContext.request.contextPath}/videos" method="get" class="advanced-search mt-3">
<input type="text" name="keyword" class="form-control" placeholder="Từ khóa tên, tác giả, mô tả..." value="${keyword}">
<input type="text" name="author" class="form-control" placeholder="Tác giả" value="${author}">
<select name="categoryId" class="form-control"><option value="">-- Tất cả danh mục --</option><c:forEach var="cat" items="${categories}"><option value="${cat.categoryId}" ${cat.categoryId == selectedCategoryId ? 'selected' : ''}>${cat.categoryName}</option></c:forEach></select>
<select name="accessLevel" class="form-control"><option value="">-- Quyền truy cập --</option><option value="PUBLIC" ${selectedAccessLevel=='PUBLIC'?'selected':''}>PUBLIC</option><option value="RESTRICTED" ${selectedAccessLevel=='RESTRICTED'?'selected':''}>RESTRICTED</option><option value="PRIVATE" ${selectedAccessLevel=='PRIVATE'?'selected':''}>PRIVATE</option></select>
<select name="status" class="form-control"><option value="">-- Trạng thái --</option><option value="AVAILABLE" ${selectedStatus=='AVAILABLE'?'selected':''}>AVAILABLE</option><option value="DISABLED" ${selectedStatus=='DISABLED'?'selected':''}>DISABLED</option></select>
<input type="hidden" name="pageSize" value="${pageSize}"><button type="submit" class="btn btn-secondary">Tìm kiếm</button><a href="${pageContext.request.contextPath}/videos" class="btn btn-secondary">Xóa lọc</a></form>
<p class="text-muted">Tìm thấy <strong>${totalVideos}</strong> video.</p>
<c:choose><c:when test="${empty videos}"><p class="text-muted">Không tìm thấy video nào.</p></c:when><c:otherwise><div class="table-wrap"><table><thead><tr><th>Tên video</th><th>Tác giả</th><th>Danh mục</th><th>Quyền</th><th>Trạng thái</th><th></th></tr></thead><tbody>
<c:forEach var="v" items="${videos}"><tr><td>${v.title}</td><td>${v.author}</td><td>${v.categoryName}</td><td><span class="badge badge-${v.accessLevel == 'PUBLIC' ? 'public' : v.accessLevel == 'RESTRICTED' ? 'restricted' : 'private'}">${v.accessLevel}</span></td><td>${v.status}</td><td><a href="${pageContext.request.contextPath}/videos/detail?id=${v.videoId}">Xem</a><c:if test="${sessionScope.currentUser.role == 'ADMIN' or sessionScope.currentUser.role == 'LIBRARIAN'}"> | <a href="${pageContext.request.contextPath}/videos/edit?id=${v.videoId}">Sửa</a> | <a href="${pageContext.request.contextPath}/videos/delete?id=${v.videoId}" onclick="return confirm('Xóa video này?');" style="color:#dc2626">Xóa</a></c:if></td></tr></c:forEach>
</tbody></table></div><c:if test="${totalPages > 1}"><div class="pagination"><c:if test="${currentPage > 1}"><a href="${pageContext.request.contextPath}/videos?keyword=${keyword}&author=${author}&categoryId=${selectedCategoryId}&accessLevel=${selectedAccessLevel}&status=${selectedStatus}&page=${currentPage-1}&pageSize=${pageSize}">← Trước</a></c:if><c:forEach var="p" begin="1" end="${totalPages}"><a class="${p==currentPage?'active':''}" href="${pageContext.request.contextPath}/videos?keyword=${keyword}&author=${author}&categoryId=${selectedCategoryId}&accessLevel=${selectedAccessLevel}&status=${selectedStatus}&page=${p}&pageSize=${pageSize}">${p}</a></c:forEach><c:if test="${currentPage < totalPages}"><a href="${pageContext.request.contextPath}/videos?keyword=${keyword}&author=${author}&categoryId=${selectedCategoryId}&accessLevel=${selectedAccessLevel}&status=${selectedStatus}&page=${currentPage+1}&pageSize=${pageSize}">Sau →</a></c:if></div></c:if></c:otherwise></c:choose>
</div></div></body></html>
