<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="fn" uri="jakarta.tags.functions" %>
<!DOCTYPE html><html lang="vi"><head><meta charset="UTF-8"><title>Admin - Permission Center</title><link rel="stylesheet" href="${pageContext.request.contextPath}/css/admin.css"></head>
<body class="admin-body"><div class="admin-shell"><%@ include file="/WEB-INF/views/admin-nav.jsp" %><main class="admin-main">
<header class="admin-head"><div><div class="eyebrow">ACCESS CONTROL</div><h1>Permission Center</h1><p>Cấp/thu hồi quyền, duyệt yêu cầu và quản lý license cho toàn bộ nội dung.</p></div></header>
<section class="panel"><div class="panel-title"><h2>⚡ Cấp quyền trực tiếp</h2></div><form method="post" action="${pageContext.request.contextPath}/admin"><input type="hidden" name="action" value="permission-grant"><div class="form-grid compact">
<label>Loại nội dung<select name="type" id="grantType" onchange="loadContentOptions()"><option>DOCUMENT</option><option>VIDEO</option><option>BOOK</option></select></label>
<label>Người dùng<select name="userId"><c:forEach var="u" items="${users}"><option value="${u.userId}">${u.username} — ${u.fullName}</option></c:forEach></select></label>
<label>Nội dung<select name="contentId" id="contentId"></select></label><label>Quyền<select name="permissionType"><option>VIEW</option><option>DOWNLOAD</option></select></label><label>Hết hạn<input type="datetime-local" name="expiryDate"></label>
</div><button class="btn primary">🔐 Cấp quyền</button></form></section>
<div class="grid2">
<section class="panel"><div class="panel-title"><h2>Requests — Document</h2><span class="count">${permissionRequests.size()}</span></div><table class="table"><thead><tr><th>User</th><th>Nội dung</th><th>Quyền</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody><c:forEach var="r" items="${permissionRequests}"><tr><td>${r.username}</td><td>${r.documentTitle}</td><td>${r.permissionType}</td><td><span class="status ${r.status=='PENDING'?'warn':r.status=='APPROVED'?'ok':'danger'}">${r.status}</span></td><td><c:if test="${r.status=='PENDING'}"><form class="inline-form" method="post" action="${pageContext.request.contextPath}/admin"><input type="hidden" name="action" value="request-approve"><input type="hidden" name="type" value="DOCUMENT"><input type="hidden" name="requestId" value="${r.requestId}"><input type="datetime-local" name="expiryDate"><button class="btn sm primary">Duyệt</button></form><form class="inline-form" method="post" action="${pageContext.request.contextPath}/admin"><input type="hidden" name="action" value="request-reject"><input type="hidden" name="type" value="DOCUMENT"><input type="hidden" name="requestId" value="${r.requestId}"><button class="btn sm danger-btn">Từ chối</button></form></c:if></td></tr></c:forEach></tbody></table></section>
<section class="panel"><div class="panel-title"><h2>Permissions — Document</h2><span class="count">${permissions.size()}</span></div><table class="table"><thead><tr><th>User</th><th>Nội dung</th><th>Quyền</th><th>Expiry</th><th></th></tr></thead><tbody><c:forEach var="p" items="${permissions}"><tr><td>${p.username}</td><td>${p.documentTitle}</td><td>${p.permissionType}</td><td>${p.expiryDate}</td><td><form method="post" action="${pageContext.request.contextPath}/admin" onsubmit="return confirm('Thu hồi quyền này?')"><input type="hidden" name="action" value="permission-revoke"><input type="hidden" name="type" value="DOCUMENT"><input type="hidden" name="permissionId" value="${p.permissionId}"><button class="btn sm danger-btn">Thu hồi</button></form></td></tr></c:forEach></tbody></table></section>
</div>
<section class="panel"><div class="panel-title"><h2>Video / Book Access</h2></div><div class="mini-stats"><span>🎬 Video permissions <b>${videoPermissions.size()}</b></span><span>📩 Video requests <b>${videoPermissionRequests.size()}</b></span><span>📚 Book permissions <b>${bookPermissions.size()}</b></span><span>📩 Book requests <b>${bookPermissionRequests.size()}</b></span></div></section>
<section class="panel"><div class="panel-title"><h2>📜 License Management</h2></div><form method="post" action="${pageContext.request.contextPath}/admin"><input type="hidden" name="action" value="license-save"><div class="form-grid compact">
<label>Loại<select name="type" id="licenseType" onchange="loadLicenseOptions()"><option>DOCUMENT</option><option>VIDEO</option><option>BOOK</option></select></label><label>Nội dung<select name="contentId" id="licenseContentId"></select></label><label>Loại license<select name="licenseType"><option>FREE</option><option>SUBSCRIPTION</option><option>PAID</option><option>INTERNAL</option></select></label><label>Mã license<input name="licenseCode" placeholder="LIC-..."></label><label>Ngày cấp<input type="date" name="issuedDate"></label><label>Ngày hết hạn<input type="date" name="expiryDate"></label><label>Trạng thái<select name="status"><option>VALID</option><option>EXPIRED</option><option>REVOKED</option></select></label><label class="full">Điều khoản<textarea name="terms" rows="2"></textarea></label></div><button class="btn primary">＋ Thêm license</button></form>
<div class="license-columns"><div><h3>Documents</h3><table class="table"><c:forEach var="l" items="${licenses}"><tr><td><b>${l.licenseCode}</b><small>${l.documentTitle}</small></td><td>${l.status}<small>${l.expiryDate}</small></td><td><form method="post" action="${pageContext.request.contextPath}/admin"><input type="hidden" name="action" value="license-revoke"><input type="hidden" name="type" value="DOCUMENT"><input type="hidden" name="licenseId" value="${l.licenseId}"><button class="btn sm">Thu hồi</button></form><form method="post" action="${pageContext.request.contextPath}/admin" onsubmit="return confirm('Xóa license?')"><input type="hidden" name="action" value="license-delete"><input type="hidden" name="type" value="DOCUMENT"><input type="hidden" name="licenseId" value="${l.licenseId}"><button class="btn sm danger-btn">Xóa</button></form></td></tr></c:forEach></table></div>
<div><h3>Video / Book</h3><p class="muted">Video licenses: <b>${videoLicenses.size()}</b> · Book licenses: <b>${bookLicenses.size()}</b></p></div></div></section>
<script>
const docs=[<c:forEach var="x" items="${documents}" varStatus="st">${st.index?',':''}{id:${x.documentId},name:'${fn:replace(x.title,"'","\\'")}'}</c:forEach>], vids=[<c:forEach var="x" items="${videos}" varStatus="st">${st.index?',':''}{id:${x.videoId},name:'${fn:replace(x.title,"'","\\'")}'}</c:forEach>], books=[<c:forEach var="x" items="${books}" varStatus="st">${st.index?',':''}{id:${x.bookId},name:'${fn:replace(x.title,"'","\\'")}'}</c:forEach>];
function opts(type,id){const a=type==='DOCUMENT'?docs:type==='VIDEO'?vids:books;document.getElementById(id).innerHTML=a.map(x=>'<option value="'+x.id+'">'+x.name+'</option>').join('')}
function loadContentOptions(){opts(document.getElementById('grantType').value,'contentId')}function loadLicenseOptions(){opts(document.getElementById('licenseType').value,'licenseContentId')}loadContentOptions();loadLicenseOptions();
</script>
</main></div></body></html>
