<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!DOCTYPE html><html lang="vi"><head><meta charset="UTF-8"><title>Admin - Cài đặt</title><link rel="stylesheet" href="${pageContext.request.contextPath}/css/admin.css"></head>
<body class="admin-body"><div class="admin-shell"><%@ include file="/WEB-INF/views/admin-nav.jsp" %><main class="admin-main">
<header class="admin-head"><div><div class="eyebrow">SYSTEM CONFIGURATION</div><h1>Cài đặt hệ thống</h1><p>Thiết lập chính sách thư viện và quyền truy cập.</p></div></header>
<form method="post" action="${pageContext.request.contextPath}/admin" class="settings-form"><input type="hidden" name="action" value="settings-save">
<section class="panel"><h2>🏛️ Thông tin thư viện</h2><div class="form-grid"><label>Tên thư viện<input name="libraryName" value="${settings.libraryName}" placeholder="CNJ25 Digital Library"></label><label>Mô tả<input name="libraryDescription" value="${settings.libraryDescription}"></label><label>Dung lượng upload tối đa (MB)<input type="number" name="maxUploadMb" min="1" value="${empty settings.maxUploadMb?50:settings.maxUploadMb}"></label></div></section>
<section class="panel"><h2>🔐 Chính sách quyền</h2><div class="form-grid"><label>Quyền mặc định<select name="defaultAccess"><option ${settings.defaultAccess=='PUBLIC'?'selected':''}>PUBLIC</option><option ${settings.defaultAccess=='RESTRICTED'?'selected':''}>RESTRICTED</option><option ${settings.defaultAccess=='PRIVATE'?'selected':''}>PRIVATE</option></select></label><label>Thời hạn quyền mặc định (ngày)<input type="number" name="permissionExpiryDays" min="0" value="${empty settings.permissionExpiryDays?30:settings.permissionExpiryDays}"></label><label>Yêu cầu duyệt quyền<select name="requireApproval"><option value="true" ${settings.requireApproval!='false'?'selected':''}>Có</option><option value="false" ${settings.requireApproval=='false'?'selected':''}>Không</option></select></label><label>Cho phép download<select name="downloadAllowed"><option value="true" ${settings.downloadAllowed!='false'?'selected':''}>Có</option><option value="false" ${settings.downloadAllowed=='false'?'selected':''}>Không</option></select></label></div></section>
<section class="panel"><h2>🛡️ Bảo mật</h2><div class="form-grid"><label>Session timeout (phút)<input type="number" name="sessionTimeout" min="5" value="${empty settings.sessionTimeout?30:settings.sessionTimeout}"></label></div></section>
<button class="btn primary">💾 Lưu cài đặt</button></form>
<c:if test="${param.success=='1'}"><div class="toast">✓ Đã lưu cài đặt hệ thống.</div></c:if>
</main></div></body></html>
