<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!DOCTYPE html><html lang="vi"><head><meta charset="UTF-8"><title>Admin - Báo cáo</title><link rel="stylesheet" href="${pageContext.request.contextPath}/css/admin.css"></head>
<body class="admin-body"><div class="admin-shell"><%@ include file="/WEB-INF/views/admin-nav.jsp" %><main class="admin-main">
<header class="admin-head"><div><div class="eyebrow">ANALYTICS</div><h1>Báo cáo & phân tích</h1><p>Nhìn nhanh sức khỏe người dùng, nội dung, quyền và truy cập.</p></div></header>
<div class="report-grid"><div class="report-card"><span>👥</span><b>${overview.users}</b><small>Người dùng</small></div><div class="report-card"><span>📚</span><b>${overview.documents+overview.books+overview.videos}</b><small>Tổng nội dung</small></div><div class="report-card"><span>👁️</span><b>${overview.accessHistory}</b><small>Lượt truy cập</small></div><div class="report-card"><span>📋</span><b>${overview.auditLogs}</b><small>Audit logs</small></div></div>
<section class="panel"><div class="panel-title"><h2>Lượt truy cập theo ngày</h2><span class="muted">7 ngày gần nhất</span></div><div class="big-bars"><c:forEach var="x" items="${accessChart}"><div class="big-bar-col"><b>${x.total}</b><div class="big-bar" style="height:${x.total*12+12}px"></div><small>${x.day}</small></div></c:forEach></div></section>
<div class="grid2"><section class="panel"><h2>Cơ cấu nội dung</h2><div class="progress-row"><span>Documents</span><b>${overview.documents}</b></div><div class="progress"><i style="width:${overview.documents*100/(overview.documents+overview.videos+overview.books+1)}%"></i></div><div class="progress-row"><span>Videos</span><b>${overview.videos}</b></div><div class="progress"><i style="width:${overview.videos*100/(overview.documents+overview.videos+overview.books+1)}%"></i></div><div class="progress-row"><span>Books</span><b>${overview.books}</b></div><div class="progress"><i style="width:${overview.books*100/(overview.documents+overview.videos+overview.books+1)}%"></i></div></section>
<section class="panel"><h2>Access Control</h2><div class="stat-list"><div><span>Permissions</span><b>${overview.permissions}</b></div><div><span>Requests pending</span><b>${overview.permissionRequests}</b></div><div><span>Licenses</span><b>${overview.licenses}</b></div><div><span>License sắp hết hạn</span><b class="text-warn">${overview.expiringLicenses}</b></div></div></section></div>
</main></div></body></html>
