<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!DOCTYPE html><html lang="vi"><head><meta charset="UTF-8"><title>Admin - Bảo mật</title><link rel="stylesheet" href="${pageContext.request.contextPath}/css/admin.css"></head>
<body class="admin-body"><div class="admin-shell"><%@ include file="/WEB-INF/views/admin-nav.jsp" %><main class="admin-main">
<header class="admin-head"><div><div class="eyebrow">SECURITY CENTER</div><h1>Bảo mật hệ thống</h1><p>Theo dõi đăng nhập lỗi, tài khoản bị khóa và hoạt động đáng chú ý.</p></div></header>
<div class="security-grid"><div class="security-card"><span>🟢</span><b>${overview.activeUsers}</b><small>Tài khoản active</small></div><div class="security-card"><span>🔒</span><b>${overview.lockedUsers}</b><small>Tài khoản locked</small></div><div class="security-card"><span>🚨</span><b>${overview.failedLogins}</b><small>Login lỗi / 24h</small></div></div>
<section class="panel"><div class="panel-title"><h2>Sự kiện đăng nhập đáng chú ý</h2><a href="${pageContext.request.contextPath}/admin/audit-logs">Tất cả audit logs →</a></div><table class="table"><thead><tr><th>Thời gian</th><th>User</th><th>Sự kiện</th><th>Mô tả</th><th>IP</th></tr></thead><tbody><c:forEach var="e" items="${events}"><tr><td>${e.createdAt}</td><td>${e.username}</td><td><span class="status danger">${e.action}</span></td><td>${e.description}</td><td>${e.ip}</td></tr></c:forEach><c:if test="${empty events}"><tr><td colspan="5" class="empty">Chưa có sự kiện bất thường.</td></tr></c:if></tbody></table></section>
<section class="panel"><h2>Khuyến nghị bảo mật</h2><div class="recommendations"><div>🔐 <b>Audit logging</b><span>Đang ghi lại thao tác quản trị và truy cập.</span></div><div>⏱️ <b>Session timeout</b><span>Thiết lập thời gian phiên trong Cài đặt hệ thống.</span></div><div>🛡️ <b>Least privilege</b><span>ADMIN quản trị qua Admin Panel, không đi vào UI nghiệp vụ của Reader.</span></div></div></section>
</main></div></body></html>
