<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!DOCTYPE html><html lang="vi"><head><meta charset="UTF-8"><title>Admin - Người dùng</title><link rel="stylesheet" href="${pageContext.request.contextPath}/css/admin.css"></head>
<body class="admin-body"><div class="admin-shell"><%@ include file="/WEB-INF/views/admin-nav.jsp" %><main class="admin-main">
<header class="admin-head"><div><div class="eyebrow">USER MANAGEMENT</div><h1>Người dùng</h1><p>Quản lý tài khoản, vai trò và trạng thái truy cập.</p></div><button class="btn primary" onclick="document.getElementById('userForm').classList.toggle('hidden')">＋ Tạo tài khoản</button></header>
<section id="userForm" class="panel ${empty editUser ? 'hidden' : ''}"><h2>${empty editUser ? 'Tạo người dùng' : 'Chỉnh sửa người dùng'}</h2>
<form method="post" action="${pageContext.request.contextPath}/admin"><input type="hidden" name="action" value="user-save"><input type="hidden" name="userId" value="${editUser.userId}">
<div class="form-grid">
<label>Username<input name="username" value="${editUser.username}" ${not empty editUser ? 'readonly' : ''} ${empty editUser ? 'required' : ''}></label>
<label>Họ tên<input name="fullName" value="${editUser.fullName}" required></label><label>Email<input type="email" name="email" value="${editUser.email}"></label>
<c:if test="${empty editUser}"><label>Mật khẩu<input type="password" name="password" required></label></c:if>
<label>Role<select name="role"><option ${editUser.role=='READER'?'selected':''}>READER</option><option ${editUser.role=='LIBRARIAN'?'selected':''}>LIBRARIAN</option><option ${editUser.role=='ADMIN'?'selected':''}>ADMIN</option><option ${editUser.role=='AUDITOR'?'selected':''}>AUDITOR</option></select></label>
<label>Trạng thái<select name="status"><option ${editUser.status=='ACTIVE'?'selected':''}>ACTIVE</option><option ${editUser.status=='LOCKED'?'selected':''}>LOCKED</option></select></label>
</div><button class="btn primary">${empty editUser ? 'Tạo tài khoản' : 'Lưu thay đổi'}</button><a class="btn" href="${pageContext.request.contextPath}/admin/users">Hủy</a></form></section>
<section class="panel"><div class="toolbar"><input id="userFilter" placeholder="🔎 Lọc theo username, tên, email..."><select id="roleFilter"><option value="">Tất cả role</option><option>ADMIN</option><option>LIBRARIAN</option><option>AUDITOR</option><option>READER</option></select><select id="statusFilter"><option value="">Tất cả trạng thái</option><option>ACTIVE</option><option>LOCKED</option></select></div>
<table class="table" id="usersTable"><thead><tr><th>ID</th><th>Người dùng</th><th>Email</th><th>Role</th><th>Trạng thái</th><th>Ngày tạo</th><th>Thao tác</th></tr></thead><tbody>
<c:forEach var="u" items="${users}"><tr data-search="${u.username} ${u.fullName} ${u.email}" data-role="${u.role}" data-status="${u.status}"><td>#${u.userId}</td><td><b>${u.fullName}</b><small>@${u.username}</small></td><td>${u.email}</td><td><span class="badge">${u.role}</span></td><td><span class="status ${u.status=='ACTIVE'?'ok':'danger'}">${u.status}</span></td><td>${u.createdAt}</td><td><div class="row-actions">
<c:if test="${u.userId != sessionScope.currentUser.userId}"><a class="btn sm" href="${pageContext.request.contextPath}/admin/users?edit=${u.userId}">Sửa</a><button type="button" class="btn sm" onclick="resetPw(${u.userId})">Đặt lại MK</button><form method="post" action="${pageContext.request.contextPath}/admin"><input type="hidden" name="action" value="user-toggle"><input type="hidden" name="userId" value="${u.userId}"><button class="btn sm">${u.status=='ACTIVE'?'Khóa':'Mở khóa'}</button></form><form method="post" action="${pageContext.request.contextPath}/admin" onsubmit="return confirm('Xóa tài khoản này?')"><input type="hidden" name="action" value="user-delete"><input type="hidden" name="userId" value="${u.userId}"><button class="btn sm danger-btn">Xóa</button></form></c:if>
</div></td></tr></c:forEach></tbody></table></section>
<script>const f=document.getElementById('userFilter'),r=document.getElementById('roleFilter'),s=document.getElementById('statusFilter');function filter(){document.querySelectorAll('#usersTable tbody tr').forEach(x=>x.style.display=((x.dataset.search||'').toLowerCase().includes(f.value.toLowerCase())&&(!r.value||x.dataset.role==r.value)&&(!s.value||x.dataset.status==s.value))?'':'none')}[f,r,s].forEach(x=>x.addEventListener('input',filter));function resetPw(id){const pw=prompt('Nhập mật khẩu mới (ít nhất 6 ký tự):');if(pw&&pw.length>=6){const f=document.createElement('form');f.method='post';f.action='${pageContext.request.contextPath}/admin';f.innerHTML='<input name="action" value="user-reset-password"><input name="userId" value="'+id+'"><input name="newPassword" value="'+pw+'">';document.body.appendChild(f);f.submit();}else if(pw!==null) alert('Mật khẩu phải có ít nhất 6 ký tự.')} </script>
</main></div></body></html>
